[org 0x7C00]

; DEFINES ;
PROGRAM_SPACE equ 0x8000
KERNEL_SECTORS equ 36

; LOAD THE KERNEL ONTO RAM ;
mov Ah, 0x02
mov Al, KERNEL_SECTORS
mov BX, PROGRAM_SPACE
mov Ch, 0x00
mov Cl, 0x02
mov Dh, 0x00
int 0x13

; JUNP OFF THE BOOTLOADER ;
jmp PROGRAM_SPACE

; INFINITE LOOP IN CASE OF FAILURE ;
jmp $

; FILL UNUSED SPACE ;
times (512 - 2) - ($ - $$) db 0
dw 0xAA55